# Generated by Django 4.2.20 on 2025-04-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, upload_to='blog_images/', verbose_name='Изображение'),
        ),
    ]
